### ISSUE TITLE
Edicion Global de productos masivos

### ISSUE THREAD

**Issue by plshazer** [plshazer/terracosmetica#50]
stock sumar
margen a preguntar si sumado o totalitario
oferta totalitario

**Comment by tomymuso** [comment]
Modal Creado.

Falta:
- [ ] Select Masivo o global.
- [ ] Traer Datos de Productos seleccionados ( IDS ). 
- [ ] Finalizar edición satisfactoria de productos.

**Comment by tomymuso** [comment]
Falta:

- [ ] Edicion individual de Costo
- [ ] - [ ] Edicion individual de Costo

**Comment by tomymuso** [comment]
Se Agrega funionalidad
